server:
  port: 8083
  

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  mvc:
    view:
      prefix: resources/templates
      suffix: html
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://dbVentasOnlineServer.mssql.somee.com;databaseName=dbVentasOnlineServer;TrustServerCertificate=True;?&useSSL=false
    username: sagender_SQLLogin_1
    password: 8badzt5se1
  jpa:
    database: SQL_SERVER
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update


        
  application:
    name: TIENDA-SERVICE
  sql:
    init:
      mode: always
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    


    