server:
  port: 8081


spring:
  
  data:
    mongodb:
      uri: mongodb+srv://manrique:epsilon5536@clusterventas.rp5x8c1.mongodb.net/?retryWrites=true&w=majority
      database: ventasOnline
  application:
    name: PRODUCTO-SERVICE
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
