server:
  port: 8082
  
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://dbAppMedicineService.mssql.somee.com;databaseName=dbAppMedicineService;TrustServerCertificate=True;?&useSSL=false
    username: vega-vv_SQLLogin_1
    password: 3fr68tjiy1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  application:
    name: OFERTA-SERVICE
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
